### ISSUE TITLE
SLK with Slack not active window, posts @ mention to the current open conversation

### ISSUE THREAD

**Issue by andyjohansson** [fspinillo/slackfred#8]
If I use the slk command and Slack is not currently the selected window (full screen mode for Slack) the command justs posts the selected group or person name as an @ mention to the conversation that is currently active.

**Comment by fspinillo** [comment]
I haven't tested this on full-screen mode. I'll take a look into it.

**Comment by andyjohansson** [comment]
Like.

**Comment by fspinillo** [comment]
I got some time to try this today and I'm pretty sure I solved this. It appears the issue is related to a delay in the Applescript. OSX seems to take a smidge longer to switch to a full screen app than a non-full screen. If you open up Alfred preferences, go to Slackfred workflow and double click on the SLK input. The Applescript just needs a delay added to it. Something like below should work:

```
on alfred_script(q)
tell application "Slack" to activate
tell application "System Events"
	delay .6
	keystroke "k" using {command down}
	tell process "Slack" to keystroke (q as string)
	key code 36
end tell
end alfred_script
```
You may need to adjust the delay as it can vary on computers and multi-monitor set up.

Let me know if this works.

**Comment by andyjohansson** [comment]
Works like an charm!
